package UI_Control;

import enity.Course;
import java.awt.Image;
import javax.swing.ImageIcon;
import picture.GetImage;
import static services.CourseServices.getPrerequisitesString;

/**
 *
 * @author admin
 */
public class ShowCourseInfo extends javax.swing.JFrame {

    /**
     * Creates new form Show
     */
    public ShowCourseInfo(Course course) {
        initComponents();
        this.course = course;
        this.setLocationRelativeTo(null);
        showInfo();
        ImageIcon icon = new ImageIcon(GetImage.class.getResource("courseinfo_icon.png"));
        Image image = icon.getImage();
        this.setIconImage(image);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        inforPanel = new javax.swing.JPanel();
        roundIDTextField = new UIcomponent.RoundJTextField();
        idLabel = new javax.swing.JLabel();
        roundNameTextField = new UIcomponent.RoundJTextField();
        referenceLabel = new javax.swing.JLabel();
        roundCreditTextField = new UIcomponent.RoundJTextField();
        creditLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        referenceTextAreaScrollPane = new javax.swing.JScrollPane();
        referenceTextArea = new javax.swing.JTextArea();

        roundStatusTextField = new UIcomponent.RoundJTextField();
        statusLabel = new javax.swing.JLabel();
        prerequisitesLabel = new javax.swing.JLabel();
        roundPrerequisitesTextField = new UIcomponent.RoundJTextField();
        gpaLabel = new javax.swing.JLabel();
        roundGPATextField = new UIcomponent.RoundJTextField();
        borderProgressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Course Information");

        titlePanel.setBackground(new java.awt.Color(204, 204, 204));

        titleLabel.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(51, 51, 51));
        titleLabel.setText("Course Progress & Information");

        inforPanel.setBackground(new java.awt.Color(2, 30, 68));

        roundIDTextField.setEditable(false);

        idLabel.setBackground(new java.awt.Color(255, 255, 255));
        idLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        idLabel.setForeground(new java.awt.Color(255, 222, 173));
        idLabel.setText("ID");

        roundNameTextField.setEditable(false);

        referenceLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        referenceLabel.setForeground(new java.awt.Color(255, 222, 173));
        referenceLabel.setText("Reference");

        roundCreditTextField.setEditable(false);

        creditLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        creditLabel.setForeground(new java.awt.Color(255, 222, 173));
        creditLabel.setText("Credit");

        nameLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 222, 173));
        nameLabel.setText("Name");

        referenceTextArea.setEditable(false);
        referenceTextArea.setBackground(new java.awt.Color(255, 255, 255));
        referenceTextArea.setColumns(20);
        referenceTextArea.setRows(5);
        referenceTextAreaScrollPane.setViewportView(referenceTextArea);

        roundStatusTextField.setEditable(false);

        statusLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        statusLabel.setForeground(new java.awt.Color(255, 222, 173));
        statusLabel.setText("Status");

        prerequisitesLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        prerequisitesLabel.setForeground(new java.awt.Color(255, 222, 173));
        prerequisitesLabel.setText("Prerequisites");

        roundPrerequisitesTextField.setEditable(false);

        gpaLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        gpaLabel.setForeground(new java.awt.Color(255, 222, 173));
        gpaLabel.setText("GPA");

        roundGPATextField.setEditable(false);

        javax.swing.GroupLayout inforPanelLayout = new javax.swing.GroupLayout(inforPanel);
        inforPanel.setLayout(inforPanelLayout);
        inforPanelLayout.setHorizontalGroup(
            inforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inforPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inforPanelLayout.createSequentialGroup()
                        .addGroup(inforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel)
                            .addComponent(idLabel))
                        .addGap(34, 34, 34)
                        .addGroup(inforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(inforPanelLayout.createSequentialGroup()
                                .addComponent(roundIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(217, 217, 217)
                                .addComponent(creditLabel))
                            .addGroup(inforPanelLayout.createSequentialGroup()
                                .addComponent(roundNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(statusLabel)))
                        .addGap(18, 18, 18)
                        .addGroup(inforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(roundCreditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roundStatusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59))
                    .addGroup(inforPanelLayout.createSequentialGroup()
                        .addGroup(inforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(inforPanelLayout.createSequentialGroup()
                                .addComponent(prerequisitesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(roundPrerequisitesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(gpaLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(roundGPATextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(inforPanelLayout.createSequentialGroup()
                                .addComponent(referenceLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(referenceTextAreaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(45, 45, 45))
            .addComponent(borderProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        inforPanelLayout.setVerticalGroup(
            inforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inforPanelLayout.createSequentialGroup()
                .addComponent(borderProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(inforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roundIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLabel)
                    .addComponent(creditLabel)
                    .addComponent(roundCreditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(inforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roundNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel)
                    .addComponent(statusLabel)
                    .addComponent(roundStatusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(inforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inforPanelLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(referenceLabel))
                    .addGroup(inforPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(referenceTextAreaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(inforPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roundPrerequisitesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prerequisitesLabel)
                    .addComponent(gpaLabel)
                    .addComponent(roundGPATextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inforPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inforPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showInfo() {
        roundIDTextField.setText(course.getID());
        roundNameTextField.setText(course.getName());
        roundPrerequisitesTextField.setText(getPrerequisitesString(course));
        roundStatusTextField.setText((course.isStatus()) ? "Completed" : "Not completed");
        roundGPATextField.setText((course.isStatus()) ? String.valueOf(course.getGPA()) : "None");
        roundCreditTextField.setText(String.valueOf(course.getCredit()));
        String reference = course.getReference();
        StringBuilder output = new StringBuilder();
        String [] toTextArea = reference.split("/");
        for (int i = 0; i < toTextArea.length; i++){
            output.append(toTextArea[i]).append("\n");
        }
        referenceTextArea.setText(output.toString());
    }
    /**
     * @param args the command line arguments
     */
    private Course course;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar borderProgressBar;
    private javax.swing.JLabel creditLabel;
    private javax.swing.JLabel gpaLabel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JPanel inforPanel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel prerequisitesLabel;
    private javax.swing.JLabel referenceLabel;
    private javax.swing.JTextArea referenceTextArea;
    private javax.swing.JScrollPane referenceTextAreaScrollPane;
    private UIcomponent.RoundJTextField roundCreditTextField;
    private UIcomponent.RoundJTextField roundGPATextField;
    private UIcomponent.RoundJTextField roundIDTextField;
    private UIcomponent.RoundJTextField roundNameTextField;
    private UIcomponent.RoundJTextField roundPrerequisitesTextField;
    private UIcomponent.RoundJTextField roundStatusTextField;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
