package UI_Control;

import UI_Control.LoginFrame;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import picture.GetImage;
import static services.AccountServices.addAccount;
import static services.AccountServices.getAccount;
import static services.AccountServices.getAccountByStudentID;
import services.IconSize_Services;

public class SignUpForm extends javax.swing.JFrame {

    public SignUpForm() {
        initComponents();
        avatarGender();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AllPanel = new javax.swing.JPanel();
        InfoFillPanel = new javax.swing.JPanel();
        fullNameTextField = new UIcomponent.RoundJTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usernameTextField = new UIcomponent.RoundJTextField();
        passwordPasswordField = new UIcomponent.RoundJTextPassword();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        signUp = new javax.swing.JLabel();
        studentIDTextField = new UIcomponent.RoundJTextField();
        jLabel7 = new javax.swing.JLabel();
        jGenderCombo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        yearAttendTextField = new UIcomponent.RoundJTextField();
        SubTitleLable = new javax.swing.JLabel();
        TitleLabel = new javax.swing.JLabel();
        imageAvatar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sign up");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AllPanel.setBackground(new java.awt.Color(2, 30, 68));

        InfoFillPanel.setBackground(new java.awt.Color(2, 30, 68));

        jLabel3.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 239, 219));
        jLabel3.setText("Full name");

        jLabel4.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 239, 219));
        jLabel4.setText("Username");

        jLabel5.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 239, 219));
        jLabel5.setText("Password");

        jLabel6.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 239, 219));
        jLabel6.setText("Year attend");

        signUp.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        signUp.setForeground(new java.awt.Color(255, 239, 219));
        signUp.setText("Sign up");
        signUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUpMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 239, 219));
        jLabel7.setText("Gender");

        jGenderCombo.setForeground(new java.awt.Color(2, 30, 68));
        jGenderCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jGenderCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jGenderComboItemStateChanged(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 239, 219));
        jLabel8.setText("Student ID");

        SubTitleLable.setBackground(new java.awt.Color(255, 255, 255));
        SubTitleLable.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        SubTitleLable.setForeground(new java.awt.Color(255, 239, 219));
        SubTitleLable.setText("Get yourself ready for the app!!!");

        javax.swing.GroupLayout InfoFillPanelLayout = new javax.swing.GroupLayout(InfoFillPanel);
        InfoFillPanel.setLayout(InfoFillPanelLayout);
        InfoFillPanelLayout.setHorizontalGroup(
            InfoFillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoFillPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InfoFillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InfoFillPanelLayout.createSequentialGroup()
                        .addGroup(InfoFillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(signUp, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(InfoFillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(InfoFillPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(yearAttendTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jGenderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, InfoFillPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(24, 24, 24)
                                    .addComponent(studentIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InfoFillPanelLayout.createSequentialGroup()
                        .addGroup(InfoFillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5))
                        .addGroup(InfoFillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InfoFillPanelLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(InfoFillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fullNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passwordPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(InfoFillPanelLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(SubTitleLable, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14))))
        );
        InfoFillPanelLayout.setVerticalGroup(
            InfoFillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoFillPanelLayout.createSequentialGroup()
                .addComponent(SubTitleLable)
                .addGap(24, 24, 24)
                .addGroup(InfoFillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fullNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(InfoFillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(InfoFillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(20, 20, 20)
                .addGroup(InfoFillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(yearAttendTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jGenderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(InfoFillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(studentIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signUp)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        TitleLabel.setFont(new java.awt.Font("Bodoni MT", 1, 31)); // NOI18N
        TitleLabel.setForeground(new java.awt.Color(255, 239, 219));
        TitleLabel.setText("Wellcome");

        imageAvatar.setText("jLabel1");

        javax.swing.GroupLayout AllPanelLayout = new javax.swing.GroupLayout(AllPanel);
        AllPanel.setLayout(AllPanelLayout);
        AllPanelLayout.setHorizontalGroup(
            AllPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AllPanelLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(TitleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(AllPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InfoFillPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(imageAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        AllPanelLayout.setVerticalGroup(
            AllPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AllPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleLabel)
                .addGroup(AllPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AllPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(InfoFillPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(AllPanelLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(imageAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        getContentPane().add(AllPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void avatarGender() {
        if (jGenderCombo.getSelectedIndex() == 0) {
            imageAvatar.setIcon(new IconSize_Services("male1.png", imageAvatar).getIcon());
        } else {
            imageAvatar.setIcon(new IconSize_Services("female.png", imageAvatar).getIcon());
        }
    }

    private void signUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpMouseClicked

        if (checkBlankSpace()) {
            String usernameText = this.usernameTextField.getText();
            String passwordText = String.valueOf(this.passwordPasswordField.getPassword());
            if (getAccount(usernameText) != null) {
                JOptionPane.showMessageDialog(this,
                        "Error this username already existed",
                        "Error",
                        JOptionPane.ERROR_MESSAGE,
                        new ImageIcon(GetImage.class.getResource("cancel.png")));
            } else {
                if (getAccountByStudentID(studentIDTextField.getText()) == null) {
                    int id = JOptionPane.showConfirmDialog(this, "Are you sure to create?");
                    if (id == JOptionPane.YES_OPTION) {
                        addAccount(usernameText,
                                passwordText,
                                fullNameTextField.getText(),
                                Integer.parseInt(yearAttendTextField.getText()),
                                studentIDTextField.getText(),
                                (jGenderCombo.getSelectedIndex() == 0) ? true : false);
                        JOptionPane.showMessageDialog(this, "Succesfull!!!");
                        new LoginFrame(usernameText).setVisible(true);
                        this.dispose();
                    }
                } else {
                    JOptionPane.showMessageDialog(this,
                            "This student ID existed",
                            "Same student ID",
                            JOptionPane.ERROR_MESSAGE,
                            new ImageIcon(GetImage.class.getResource("cancel.png")));
                }

            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "Please fill every box",
                    "Error",
                    JOptionPane.ERROR_MESSAGE,
                    new ImageIcon(GetImage.class.getResource("cancel.png")));
        }
    }//GEN-LAST:event_signUpMouseClicked

    private void jGenderComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jGenderComboItemStateChanged
        avatarGender();
    }//GEN-LAST:event_jGenderComboItemStateChanged

    public boolean checkBlankSpace() {
        if (usernameTextField.getText().equals("")
                || String.valueOf(passwordPasswordField.getPassword()).equals("")
                || fullNameTextField.getText().equals("")
                || yearAttendTextField.getText().equals("")
                || studentIDTextField.getText().equals("")) {
            return false;
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AllPanel;
    private javax.swing.JPanel InfoFillPanel;
    private javax.swing.JLabel SubTitleLable;
    private javax.swing.JLabel TitleLabel;
    private UIcomponent.RoundJTextField fullNameTextField;
    private javax.swing.JLabel imageAvatar;
    private javax.swing.JComboBox<String> jGenderCombo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private UIcomponent.RoundJTextPassword passwordPasswordField;
    private javax.swing.JLabel signUp;
    private UIcomponent.RoundJTextField studentIDTextField;
    private UIcomponent.RoundJTextField usernameTextField;
    private UIcomponent.RoundJTextField yearAttendTextField;
    // End of variables declaration//GEN-END:variables
}
